# Generated by Django 4.0 on 2021-12-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0002_passwords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='passwords',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='passwords',
            name='name',
        ),
        migrations.AddField(
            model_name='passwords',
            name='encrypted_key',
            field=models.TextField(default='enc_dummy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwords',
            name='encrypted_password',
            field=models.TextField(default='enc_pass_dummy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwords',
            name='url',
            field=models.URLField(default='http://www.facebook.com'),
            preserve_default=False,
        ),
    ]
