# Generated by Django 4.0 on 2021-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0003_rename_passwords_passwords_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
