# Generated by Django 4.0 on 2021-12-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0004_passwords_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords',
            name='name',
        ),
        migrations.AddField(
            model_name='passwords',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwords',
            name='websitename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
