# Generated by Django 4.0 on 2021-12-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0005_remove_passwords_name_passwords_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='username',
            new_name='websiteusername',
        ),
    ]
