# Generated by Django 4.0 on 2021-12-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('PasswordManager', '0006_rename_username_passwords_websiteusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decrypted_key', models.TextField()),
                ('encrypted_key', models.TextField()),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PasswordManager.passwords')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sender_user', to='auth.user')),
            ],
        ),
    ]
