# Generated by Django 4.0 on 2021-12-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_private_key',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.TextField(default='2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='decrypted_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_key',
            field=models.TextField(blank=True),
        ),
    ]
